### ISSUE TITLE
windows install location issue, maybe the wrong place

### ISSUE THREAD

**Issue by sigmap** [Tiamarth/Arc-for-Vivaldi#1]
the suggested location doesn't exactly exist for me
The only thing I found in `AppData\Local\Vivaldi` was `userdata`
any ideas where to go from here?

**Comment by Tiamarth** [comment]
It hadn't occurred to me while writing the install instructions, but it might vary depending on Windows version. Unfortunately I don't have access to a Windows machine to figure it out myself, but I can point you to a couple of places online that might help

https://forum.vivaldi.net/topic/10549/modding-vivaldi

https://www.reddit.com/r/vivaldibrowser/comments/6uytw8/custom_css_just_not_doing_anything/

https://www.reddit.com/r/vivaldibrowser/comments/4g7tz9/tiny_panel_custom_css/

https://www.ghacks.net/2017/03/15/intro-to-customizing-vivaldis-interface-with-css/

I know this is a really late reply to your issue, and I apologize, but I'd appreciate it if you (or someone else) could get back to me on this so I can update the readme with the correct location.
