### ISSUE TITLE
Tabs minimal width too big

### ISSUE THREAD

**Issue by TimsManter** [Tiamarth/Arc-for-Vivaldi#3]
I found an issue with my customization setup. When tabs panel is set to right (or left) and there are enough tabs that scroll bar appears (for tabs) and tabs panel width is set to minimum then tabs panel is too wide thus some text (half a single letter) is showing next to favicon.

Vanilla | Arc for Vivaldi
--- | ---
![screenshot from 2018-06-03 11-59-45](https://user-images.githubusercontent.com/5507688/40885496-90b15248-6727-11e8-903c-b72afac51d74.png) | ![screenshot from 2018-06-03 12-14-52](https://user-images.githubusercontent.com/5507688/40885510-d21fd7c2-6727-11e8-9f78-25c1a20322da.png)

This issue is caused by Vivaldi's behavior as when there's enough room for tabs the minimum width of tabs panel is the width of favicon but when scroll bar appears it's favicon width + scroll bar width. In Arc theme scroll bar is thinner hence this bug.

It's not a big deal but feels like grain in the eye and maybe can be fixed in CSS.

**Comment by Tiamarth** [comment]
This will probably be really easy to fix, but I won't have time to look at it until tomorrow
